# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Ecommerce.create(user_id: 1, 
#                  title: "",
#                  image_main: "", 
#                  image_01:"",
#                  image_02:"",
#                  image_03:"",
#                  image_04:"",
#                  intro: "",
#                  site_link: "",
#                  price_before: "",
#                  price_after: "",
#                  youtube_link_01: "",
#                  youtube_link_02: "",
#                  description: "",      
#                  description_01: "",
#                  description_02: "",
#                  description_03: "",
#                  description_04: "",
#                  description_05: "")   

Ecommerce.create(user_id: 1, 
                 title: "Prynt",
                 image_main: "https://d21buns5ku92am.cloudfront.net/47910/images/160353-Prynt%20and%20photos-0e39c8-large-1427155286.png", 
                 image_01:"http://travel-ling.com/wp-content/uploads/2016/10/20161007_191518-1.jpg",
                 image_02:"https://cnet2.cbsistatic.com/img/tH4CKPFPP1dCzvZJFulHdKLuPeA=/1600x900/2017/05/22/5b64d36a-3a48-4674-9cd1-04ac65a6502d/graphite-lifestyle-3.png",
                 image_03:"http://www.girlabouttech.com/wp-content/uploads/2015/01/Prynt-In-Action-_-girlabouttech.com_.jpg",
                 image_04:"https://d39ya6rrfzruz.cloudfront.net/production/assets/home/Scan-d78080a3c2634150bc4d12d96742a286.gif",
                 intro: "Print instant photos from your phone! Simply attach the Prynt Case to your phone, take a photo and then create a short video. Then, print it out! When you hand your Prynt photo to a friend, they can use the Prynt app to unlock the hidden video clip, magically bringing your Prynt photo to life!",
                 site_link: "http://amzn.to/2es5aT6",
                 price_before: "",
                 price_after: "144.90",
                 youtube_link_01: "https://www.youtube.com/embed/tUi7gFgEn8Q",
                 youtube_link_02: "https://www.youtube.com/embed/k_BZup8XFiM",
                 description: "The Prynt Pocket turns your iPhone into a palm-sized instant camera. Print any photo saved to your phone or favorite social networks, anywhere. But there's more. The Prynt app enables you to add a video inside your photo. When you share your Prynt photo with friends, they can use the Prynt app to unlock the video clip, magically bringing your Prynt photo to life!",
                 description_01: "Turn your iPhone into an instant camera ½ the size of the original Prynt Case, with an easy-to-remove paper cartridge",
                 description_02: "Print photos from your phone (even Instagram), or take new ones- printed in 30 seconds",
                 description_03: "Add a video to your Prynt and watch it come to life with the app",
                 description_04: "No ink necessary- photos are printed directly onto ZINK (zero ink) Sticker Paper- the only photo paper compatible with Prynt Pocket",
                 description_05: "Peel off the adhesive backing to turn any photo into a sticker!Compatible with the Apple iPhone 7 Plus, iPhone 7, iPhone SE, iPhone 6s Plus, iPhone 6s, iPhone 6 Plus, iPhone 5s, iPhone 5")

           
Ecommerce.create(user_id: 1, 
                 title: "EcoDot",
                 image_main: "https://cnet2.cbsistatic.com/img/rBFEZeQLNwn1b8C-ef9UBzeijcU=/770x433/2016/09/29/25e69ef0-1367-4036-9df4-1c9d6924afed/new-echo-dot-product-photos-3.jpg", 
                 image_01:"https://content.jwplatform.com/thumbs/kVUfBnXl.jpg",
                 image_02:"https://i.ebayimg.com/00/s/MTAwMFgxMDAw/z/FmEAAOSw2gxYwgHv/$_86.JPG",
                 image_03:"http://cdn04.androidauthority.net/wp-content/uploads/2016/03/Amazon-Echo-Dot.jpg",
                 image_04:"https://cnet4.cbsistatic.com/img/kT0py77IbTrhIYwNqwcBJgd0XZw=/770x433/2016/09/30/a157d124-8f22-4a29-bab4-252a968fbfa2/echo-dot-comparison-shots-1.jpg",
                 intro: "Echo Dot is a hands-free, voice-controlled device with a small built-in speaker—it can also connect to your speakers or headphones over Bluetooth or through a 3.5 mm audio cable to deliver stereo sound to the speakers you choose. Dot connects to the Alexa Voice Service to play music, make calls, send and receive messages, provide information, news, sports scores, weather, and more—instantly.",
                 site_link: "http://amzn.to/2wvkKWt",
                 price_before: "",
                 price_after: "44.00",
                 youtube_link_01: "https://www.youtube.com/embed/hPXS7rC1PWo",
                 youtube_link_02: "https://www.youtube.com/embed/7Ms_FTVxNrk",
                 description: "Echo Dot can hear you from across the room, even while music is playing. When you want to use Echo Dot, just say the wake word “Alexa” and Dot responds instantly. If you have more than one Echo or Echo Dot, Alexa responds intelligently from the Echo you're closest to with ESP (Echo Spatial Perception).
                               Sleek and compact design makes Echo Dot a convenient addition to any room in the house. With its built-in speaker, you can place Dot in the bedroom and use it as a smart alarm clock that can also turn off your lights. Or use Dot in the kitchen to easily set timers and shop tens of millions of Amazon products using just your voice.",
                 description_01: "Echo Dot (2nd Generation) is a hands-free, voice-controlled device that uses Alexa to play music, control smart home devices, make calls, send and receive messages, provide information, read the news, set alarms, read audiobooks from Audible, control Amazon Video on Fire TV, and more",
                 description_02: "Connects to speakers or headphones through Bluetooth or 3.5 mm stereo cable to play music from Amazon Music, Spotify, Pandora, iHeartRadio, and TuneIn. Play music simultaneously across Echo devices and speakers connected via cable with multi-room music (Spotify and Sirius XM support coming soon, Bluetooth not supported).",
                 description_03: "Introducing Alexa calling and messaging, a new way to be together with family and friends. Just ask Alexa to call or message anyone with an Echo, Echo Dot, or the Alexa App.",
                 description_04: "Controls lights, fans, TVs, switches, thermostats, garage doors, sprinklers, locks, and more with compatible connected devices from WeMo, Philips Hue, Sony, Samsung SmartThings, Nest, and others",
                 description_05: "Hears you from across the room with 7 far-field microphones for hands-free control, even in noisy environments or while playing music")
                 
Ecommerce.create(user_id: 1, 
                 title: "Tile Mate",
                 image_main: "http://i1128.photobucket.com/albums/m488/onesmileymonkey/Blog/Blog/IMG_1301_zpsuwxwtabp.jpg", 
                 image_01:"https://www.frugalcouponliving.com/wp-content/uploads/2017/02/tile-mate.jpg",
                 image_02:"http://digitalspyuk.cdnds.net/16/41/980x490/landscape-1476197985-tile.png",
                 image_03:"https://www.verizon.com/home/accessories/media/images-accessories/vzw/tile-tilemate-bluetooth-tracker-4-pack-c-tilemate4pk.png",
                 image_04:"http://www.citizentekk.com/wp-content/uploads/2017/05/Tile-Slim-Mens-Wallet.png",
                 intro: "Never Lose Your Keys, Phone, Or Anything Again. Tile Mate has a convenient hole, perfect for attaching to your keys, purse, backpack and more. Now, you can easily find all your important things.",
                 site_link: "http://amzn.to/2xQl6a8",
                 price_before: "$24.99",
                 price_after: "22.25",
                 youtube_link_01: "https://www.youtube.com/embed/dxyajtakhPg",
                 youtube_link_02: "https://www.youtube.com/embed/gG5WTcgzPv4",
                 description: "Tile Mate is the easiest, quickest and most reliable way to find your phone, keys — anything! With over 5 million Tile devices sold, the Tile community is the world’s largest lost and found network.",      
                 description_01: "The world’s best-selling Bluetooth tracker just got 25% smaller. Tile Mate easily loops onto keychains or attaches to anything you don’t want to lose so you can find it fast.",
                 description_02: "Ring your things.Use your smartphone to make your Tile Mate ring when it’s nearby but out of sight.Ask others to help. Your Tile isn’t where you left it?  You can anonymously enlist help in the Tile community. With over 5 million Tile devices sold, it is the world’s largest lost and found network.",
                 description_03: "Find your phone. Can't find your phone? Simply double press the button on your Tile Mate to make your phone ring -even on silent!",
                 description_04: "See where you had it last. The easy-to-use, free Tile app remembers the last time and place it saw your Tile, so if you left it somewhere, you’ll always know where to look.",
                 description_05: "Battery life:One year from shipment: Charging:None All activity measurements and calculations are estimates. Accuracy is affected by various factors including physiology, location of device, and different movements.")

Ecommerce.create(user_id: 1, 
                 title: "UO Smart Beam Laser",
                 image_main: "https://awesomestuff365.com/wp-content/uploads/2017/05/UO-Smart-Beam-Mini-Portable-Projector-3.jpg", 
                 image_01:"https://awesomestuff365.com/wp-content/uploads/2017/05/UO-Smart-Beam-Mini-Portable-Projector-3.jpg",
                 image_02:"https://portablebuddy.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/u/o/uosmartbeamlaser_7.jpg",
                 image_03:"http://www.earlyadopter.co.kr/wp-content/uploads/2016/11/uo-smartbeam-laser-nx-bigbang-10th-anniversary-edition-projector-4.jpg",
                 image_04:"https://images-na.ssl-images-amazon.com/images/I/614-SbGxifL._SY400_.jpg",
                 intro: "This is the first and best laser projector which stay focused all the time so you can enjoy sharp vivid color images whenever and wherever you want.",
                 site_link: "http://amzn.to/2vOGvDj",
                 price_before: "$435.00",
                 price_after: "345.00",
                 youtube_link_01: "https://www.youtube.com/embed/0nw2PRDX5l0",
                 youtube_link_02: "https://www.youtube.com/embed/o6UmcKlkdAk",
                 description: "UO Smart Beam Laser is world's One and Only FDA-Registered Class 1 Eye-safe Laser Projector and 2016 CES Innovative Product Award Winner. It's completely safe for human eye. Portable 2 inch cube projects up to 150 inch HD screen in complete dark area. Simply connect UO with Wi-Fi or cables to smartphone, tablet, laptop, pc, media player or any other devices to play video, audio, picture, presentation, etc. Use it on any surface at anytime and anywhere because it's portable Wi-Fi Wireless & FOCUS FREE!",      
                 description_01: "Variety Compatibility - UO Smart Beam Laser is compatible to use with variety devices using Wi-Fi or cables such as Android, iOS, smartphone, tablet, laptop, computer, game console, media player, action camera, etc.",
                 description_02: "Auto Focus with Eye Safe Laser - UO Smart Beam Laser is world's 1st and best laser portable projector with eye safe class 1 laser and it’s the only projector with FDA registration in the world. It’s auto focus projector because of laser technology.",
                 description_03: "Variety Applications - UO Smart Beam Laser is portable light weight wireless HD projector that you can carry it anytime, anywhere and project it on any surface. Use it as home theatre, outdoor camping, group meeting, business presentation, education and so on.",
                 description_04: "Until now, most projectors used either LED, LCD or DLP as the light source and they all possessed one bothersome problem: Focus needed to be adjusted manually. This was especially a big problem for portable projectors since they were meant to be carried around and the user had to adjust the focus every single time",
                 description_05: "The team behind the creation of UO Smart Beam Laser invented a highly-advanced laser technology that is completely safe to human eye. The Class 1 Laser used in the projector is registered with FDA. UO Smart Beam Laser's ingenious focus free and harmless laser technology has earned itself the 2016 CES Innovative Award")        
             
Ecommerce.create(user_id: 1, 
                 title: "MiniPresso GR Espresso Maker",
                 image_main: "http://cdn.thefunnybeaver.com/wp-content/uploads/2017/05/MiniPresso-GR-Espresso-Maker-review-and-price-Featured.jpg", 
                 image_01:"https://images-na.ssl-images-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/A2BK7LPF7A0UPQ/B00VTA9F6U/e89I6RzSRQGk._UX900_TTW_.jpg",
                 image_02:"https://m.media-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/A2BK7LPF7A0UPQ/B00VTA9F6U/3SfwueQ4RVW._UX300_TTW__.jpg",
                 image_03:"https://m.media-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/A2BK7LPF7A0UPQ/B00VTA9F6U/uxwLYT6TNKQ._CR148,0,591,595_UX300_TTW__.jpg",
                 image_04:"https://ae01.alicdn.com/kf/HTB1.HBAMFXXXXcoXFXXq6xXFXXXA/china-WACACO-font-b-Minipresso-b-font-outdoor-font-b-portable-b-font-coffee-machine-manual.jpg",
                 intro: "With a Minipresso GR, you can pour high quality espresso anywhere on the go.  At under 1lb and 7inch long, it fits in your backpack, carry on luggage, glove box, or desk drawer. Pull amazing shots on your schedule, waking up or the craving just hits.",
                 site_link: "http://amzn.to/2ePbF6p",
                 price_before: "$64.99",
                 price_after: "52.00",
                 youtube_link_01: "https://www.youtube.com/embed/CrmqX6e22Aw",
                 youtube_link_02: "https://www.youtube.com/embed/4vqtEZQE7-I",
                 description: "We are taking espresso on the road, way beyond the confines of the cafe. Whether you sleep in a tent, a hotel bed, or at home, Minipress has you covered for your ritual morning cup. Forget the pot they call coffee in the office break room. Enjoy an espresso, or two, in the time it takes standing in line at the coffee shop, at a fraction of the cost.",      
                 description_01: "The Minipresso GR uses ground beans, and you need a source for hot water, a tea kettle for example. Be your own barista. ",
                 description_02: "The Minipresso is hand powered.There is no electric cord, and no batteries are required. Never find yourself out of power out of luck. I  want a shot and I want it now!",
                 description_03: "6 peices in all, including a scooper for measured extraction. Food grade plastic and BPA free. The GR model is for use with ground beans only, not coffee capsules.  ",
                 description_04: "Minipresso can make espresso anywhere.",
                 description_05: "Minipresso has a sleek modern design and intuitive operation,")                    
                 
Ecommerce.create(user_id: 1, 
                 title: "Collar Perfect",
                 image_main: "https://ksr-ugc.imgix.net/assets/004/960/314/a05920e59074547ee9a1d472a65ec838_original.jpg?w=700&fit=max&v=1448228813&auto=format&q=92&s=c12dd24c0e6c29ca947e59350b298476", 
                 image_01:"https://images-na.ssl-images-amazon.com/images/G/01/vince/boost/detailpages/collarperfectvideo._SR720,404_.jpg",
                 image_02:"https://images-na.ssl-images-amazon.com/images/G/01/vince/boost/detailpages/collarperfect2._SR300,300_.jpg",
                 image_03:"https://images-na.ssl-images-amazon.com/images/G/01/vince/boost/detailpages/collarperfect3._SR300,300_.jpg",
                 image_04:"https://images-na.ssl-images-amazon.com/images/G/01/vince/boost/detailpages/collarperfect4a.jpg",
                 intro: "Collar Perfect is a compact and quick ironing solution that works by clamping onto collars, cuffs, creases, between buttons, and other parts to smooth out wrinkles. What makes it Perfect is the ability to transform by opening to flatten the wings for use like a regular iron. Collar Perfect comes with five adjustable temperature settings and international power support to iron out all of life's wrinkles.",
                 site_link: "http://amzn.to/2wd4O9w",
                 price_before: "",
                 price_after: "34.95 ",
                 youtube_link_01: "https://www.youtube.com/embed/0NfNc8FuyHw",
                 youtube_link_02: "https://www.youtube.com/embed/zV_C4vwkjTU",
                 description: "",      
                 description_01: "Perfect for Quick Touch Ups and Hard to Reach Places - The unique design allows for quick and easy touch ups along pesky shirt collars, between buttons, along pant creases, and other hard to reach areas.",
                 description_02: "Convertible Wings are Perfect for Detailed Ironing - The convertible wings rotate for traditional ironing on the fly for when you need more than a quick touch up.",
                 description_03: "Adjustable Heat Settings - Six adjustable heat settings perfect for any fabric.",
                 description_04: "Powered for Travel - Built in support for either 110v or 220v requirements.",
                 description_05: "Rotating Power Cord - Rotating Power Cord perfect to provide improved user ability in detailing and ironing needs.")  

Ecommerce.create(user_id: 1, 
                 title: "Cozmo",
                 image_main: "https://i.ytimg.com/vi/k_hvLYxxaNg/maxresdefault.jpg", 
                 image_01:"https://cdn.vox-cdn.com/thumbor/WpBfiuZjjcj2X0EzaXdtJPeschM=/40x0:1390x900/1200x800/filters:focal(40x0:1390x900)/cdn.vox-cdn.com/uploads/chorus_image/image/49959931/anki-cozmo-04_1600.0.0.jpg",
                 image_02:"https://s.aolcdn.com/hss/storage/midas/69be669b7fd70fa1eafb0efa73bdda36/204617745/1121_cozmo.jpg",
                 image_03:"https://timedotcom.files.wordpress.com/2016/10/cozmo-gif.gif?w=560",
                 image_04:"https://68.media.tumblr.com/59d5aa4a85734fa3628122677ef639f8/tumblr_ofcnbhkcqp1vnq1cro1_400.gif",
                 intro: "Only the coolest robot ever invented. Say Hello to cozmo, a gifted little guy who's got a mind of his own and a few tricks up his sleeve. He's the sweet spot where supercomputer meets loyal sidekick. He's curiously smart, a little mischievous, and unlike anything ever created. You see, cozmo is a real-life robot like you've only seen in movies, with a one-of-a-kind personality that evolves the more you hang out. He'll nudge you to play and keep you constantly surprised. More than a companion, cozmo's a collaborator. He's your accomplice in a crazy amount of fun. Some robots just have it all.",
                 site_link: "http://amzn.to/2gOLD3J",
                 price_before: "",
                 price_after: "179.99",
                 youtube_link_01: "https://www.youtube.com/embed/eBp10ylItlw",
                 youtube_link_02: "https://www.youtube.com/embed/IrrCUoMi0sM",
                 description: "",      
                 description_01: "Adorably personable - He’s a supercomputer and loyal sidekick all at once. Thanks to artificial intelligence, Cozmo can express hundreds of emotions. From curious to clever, persistent to playful, he has personality x 10. He knows your name, face, and quirks. And best of all, he continues to evolve the more you hang out.",
                 description_02: "Super-powered smarts - Cozmo is made of 300+ parts that create one super smart, super entertaining robot. He doesn’t just move; he gets curious and explores. He doesn’t just learn; he plots and plans. He doesn’t just see you; he gets to know you. Want to see Cozmo do something totally new? Use the Cozmo Software Developers Kit (SDK) to program new interactions.",
                 description_03: "Always game - Cozmo is a game-playing machine. Literally. Whether lifting his Power Cubes or challenging you to games like Quick Tap and Keepaway, he’s always up for action. And in Explorer Mode, Cozmo lets you guide him through his environment to see what he sees — day or night. Cozmo’s skills and games are constantly updating, so the fun never runs out.",
                 description_04: "Ready to roll - Drop-tested and built to last, Cozmo is tougher than he looks (even when it comes to your pup). Things like safety and data security have also been rigorously tested. With no parts to put together, he’s ready to go right out of the box. Requires a compatible iOS or Android device and the free Cozmo app.",
                 description_05: "WARNING: CHOKING HAZARD -- Small parts. Not for children under 3 yrs.")                


